apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mono-repo-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/stjernstrom/test-infra
        revision: main
        directories:
          - path: applications/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/stjernstrom/test-infra
        path: "{{path}}"
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: cilium.io
          kind: CiliumIdentity
