# This manifest written by Jolene Engo <dev.toaster@gmail.com>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    helm:
      parameters:
        - name: crds.enabled
          value: "true"
        - name: prometheus.enabled
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

