# This manifest written by Jolene Engo <dev.toaster@gmail.com>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"name":"cert-manager","namespace":"argocd"},"spec":{"project":"default","source":{"repoURL":"https://charts.jetstack.io","chart":"cert-manager","targetRevision":"v1.13.0"},"destination":{"server":"https://kubernetes.default.svc","namespace":"cert-manager"},"syncPolicy":{"automated":true}}}
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

