apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.com`)
      kind: Rule
      services:
        - name: my-app
          port: 80
  tls:
    certResolver: letsencrypt
